apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  labels:
    io.fynarfin.service: service
  name: service
  namespace: odk  
spec:
  replicas: 1
  selector:
    matchLabels:
      io.fynarfin.service: service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.fynarfin.service: service
    spec:
      containers:
        - args:
            - ./wait-for-it.sh
            - postgres:5432
            - --
            - ./start-odk.sh
          env:
            - name: DOMAIN
              #value: "testing-odk-nginx.ibank.financial"
              value: "95396097-us-east.lb.appdomain.cloud"
            - name: SYSADMIN_EMAIL
              value: "ntando@fynarfin.io"
          image: ntando/odk-central-service:latest
          name: service
          ports:
            - containerPort: 8383          
          resources:
            requests:
              memory: "256Mi"
              cpu: "512m"
            limits:
              memory: "256Mi"
              cpu: "512m"           
          volumeMounts:
            - mountPath: /etc/secrets
              name: secrets-configmap
            - mountPath: /data/transfer
              name: service-claim1
      restartPolicy: Always
      volumes:
        - name: secrets-configmap
          configMap:
            name: secrets-configmap
        - name: service-claim1
          persistentVolumeClaim:
            claimName: service-claim1
status: {}
